//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZHK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartament
    {
        public Apartament()
        {

        }

        public Apartament(short iD, byte houseID, short number, decimal area, byte countOfRooms, byte section, byte floor, bool? isSold, int? buildingCost, int? apartmentValueAdded, byte? isDeleted)
        {
            ID = iD;
            HouseID = houseID;
            Number = number;
            Area = area;
            CountOfRooms = countOfRooms;
            Section = section;
            Floor = floor;
            IsSold = isSold;
            BuildingCost = buildingCost;
            ApartmentValueAdded = apartmentValueAdded;
            IsDeleted = isDeleted;
        }

        public short ID { get; set; }
        public byte HouseID { get; set; }
        public short Number { get; set; }
        public decimal Area { get; set; }
        public byte CountOfRooms { get; set; }
        public byte Section { get; set; }
        public byte Floor { get; set; }
        public Nullable<bool> IsSold { get; set; }
        public Nullable<int> BuildingCost { get; set; }
        public Nullable<int> ApartmentValueAdded { get; set; }
        public Nullable<byte> IsDeleted { get; set; }
    
        public virtual House House { get; set; }
    }
}
